# Generated by Django 5.0 on 2024-01-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='Drinks',
            field=models.CharField(default='Drinks', max_length=122),
        ),
    ]
