# Generated by Django 5.0 on 2024-01-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_res_drinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='Dishes',
            field=models.CharField(default='Dishes', max_length=122),
        ),
        migrations.AddField(
            model_name='res',
            name='Soups',
            field=models.CharField(default='Soups', max_length=122),
        ),
    ]
